module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Tamil-inspired palette
        'tamil-orange': '#FF5C01',
        'tamil-red': '#B01432',
        'tamil-yellow': '#FFA900',
        'tamil-saffron': '#EECF1A',
        'tamil-gold': '#F0A936',
        'primary': {
          DEFAULT: '#FF5C01',
          hover: '#E64A00',
          active: '#CC4200',
        },
        'secondary': {
          DEFAULT: '#FFA900',
        },
        'accent': '#B01432',
        'saffron': '#EECF1A',
        'gold': '#F0A936',
        'surface': '#FFFFFD',
        'background': '#FCFCF9',
        'text': '#13343B',
        'text-secondary': '#626C71',
        'card-border': 'rgba(94,82,64,0.12)',
        'border': 'rgba(94,82,64,0.2)',
        'success': '#21808D',
        'error': '#C0152F',
        'info': '#626C71',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #FF5C01 0%, #FFA900 100%)',
        'gradient-secondary': 'linear-gradient(135deg, #B01432 0%, #FF5C01 100%)',
        'gradient-accent': 'linear-gradient(135deg, #FFA900 0%, #EECF1A 100%)',
      },
      fontFamily: {
        sans: [
          'FKGroteskNeue',
          'Geist',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        tamil: [
          'Noto Sans Tamil',
          'Inter',
          'sans-serif',
        ],
      },
      fontSize: {
        xs: '11px',
        sm: '12px',
        base: '14px',
        md: '14px',
        lg: '16px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '30px',
        'hero': '3rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '550',
        bold: '600',
      },
      lineHeight: {
        tight: '1.2',
        normal: '1.5',
      },
      letterSpacing: {
        tight: '-0.01em',
      },
      spacing: {
        0: '0',
        1: '1px',
        2: '2px',
        4: '4px',
        6: '6px',
        8: '8px',
        10: '10px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '8px',
        md: '10px',
        lg: '12px',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0,0,0,0.02)',
        sm: '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02)',
        md: '0 4px 6px -1px rgba(0,0,0,0.04), 0 2px 4px -1px rgba(0,0,0,0.02)',
        lg: '0 10px 15px -3px rgba(0,0,0,0.04), 0 4px 6px -2px rgba(0,0,0,0.02)',
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.16,1,0.3,1)',
      },
      maxWidth: {
        'container-sm': '640px',
        'container-md': '768px',
        'container-lg': '1024px',
        'container-xl': '1280px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        'slide-up': {
          '0%': { transform: 'translateY(40px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        'pulse-custom': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.08)' },
        },
        'bounce-custom': {
          '0%, 100%': { transform: 'translateY(0)' },
          '20%': { transform: 'translateY(-8px)' },
          '40%': { transform: 'translateY(0)' },
          '60%': { transform: 'translateY(-4px)' },
          '80%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
        'slide-up': 'slide-up 0.5s cubic-bezier(0.16,1,0.3,1)',
        'pulse-custom': 'pulse-custom 0.6s cubic-bezier(0.4,0,0.6,1)',
        'bounce-custom': 'bounce-custom 0.6s',
      },
    },
  },
  plugins: [],
}; 